Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('CM3/CoreSupport/*.c')
src += Glob('CM3/DeviceSupport/fujitsu/mb9bf61x/*.c')

CPPPATH = [cwd + '/CM3/CoreSupport', cwd + '/CM3/DeviceSupport/fujitsu/mb9bf61x/']

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
	src += ['CM3/DeviceSupport/fujitsu/mb9bf61x/startup/gcc/startup_mb9bf61x.S']
elif rtconfig.CROSS_TOOL == 'keil':
	src += ['CM3/DeviceSupport/fujitsu/mb9bf61x/startup/arm/startup_mb9bf61x.S']
elif rtconfig.CROSS_TOOL == 'iar':
	src += ['CM3/DeviceSupport/fujitsu/mb9bf61x/startup/iar/startup_mb9bf61x.S']

CPPDEFINES = [rtconfig.FM3_TYPE]
group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
